/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Aluno.Aluno;
import Professor.Professor;
import Professor.Titulacao;
import Turma.Turma;
import Turma.Turno;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Boos
 */
public class Tela1TurmaProfessor extends javax.swing.JFrame {
    
    DecimalFormat format = new DecimalFormat("#.##");
    
    private String nomeAluno;

    /**
     * Creates new form Tela1TurmaProfessor
     */
    public Tela1TurmaProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTurno = new javax.swing.ButtonGroup();
        btnGroupTitulacao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFDisciplina = new javax.swing.JTextField();
        jRBMatutino = new javax.swing.JRadioButton();
        jRBVespertino = new javax.swing.JRadioButton();
        jRBNoturno = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFNomeProfessor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFEmailProfessor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRBGraduacao = new javax.swing.JRadioButton();
        jRBMestrado = new javax.swing.JRadioButton();
        jRBDoutorado = new javax.swing.JRadioButton();
        jBtnListarDados = new javax.swing.JButton();
        jBtnIncluirAluno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Disciplina:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Turno:");

        btnGroupTurno.add(jRBMatutino);
        jRBMatutino.setText("Matutino");

        btnGroupTurno.add(jRBVespertino);
        jRBVespertino.setText("Vespertino");

        btnGroupTurno.add(jRBNoturno);
        jRBNoturno.setText("Noturno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFDisciplina)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBMatutino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRBVespertino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jRBNoturno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRBMatutino)
                    .addComponent(jRBVespertino)
                    .addComponent(jRBNoturno))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Titulação:");

        btnGroupTitulacao.add(jRBGraduacao);
        jRBGraduacao.setText("Graduação");

        btnGroupTitulacao.add(jRBMestrado);
        jRBMestrado.setText("Mestrado");

        btnGroupTitulacao.add(jRBDoutorado);
        jRBDoutorado.setText("Doutorado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTFNomeProfessor)
                        .addComponent(jTFEmailProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRBGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBMestrado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBDoutorado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFEmailProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRBGraduacao)
                    .addComponent(jRBMestrado)
                    .addComponent(jRBDoutorado))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jBtnListarDados.setText("Listar Dados da Turma");
        jBtnListarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarDadosActionPerformed(evt);
            }
        });

        jBtnIncluirAluno.setText("Incluir Aluno");
        jBtnIncluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jBtnIncluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnListarDados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIncluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnListarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean turmaCadastrada = false;
    Turma turma;
    Professor professor;
    
    private void jBtnIncluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirAlunoActionPerformed
        cadastrarTurma();
        
        Tela2Aluno tela2 = new Tela2Aluno(Tela1TurmaProfessor.this);
        tela2.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirAlunoActionPerformed

    private void jBtnListarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarDadosActionPerformed
        cadastrarTurma();
        
        String disciplina = turma.getDisciplina();
        Turno turno = turma.getTurno();
        String strTurno = turnoParaStr(turno);
        
        String nomeProfessor = turma.getProfessor().getNome();
        Titulacao titulacao = turma.getProfessor().getTitulacao();
        String strTitulacao = titulacaoParaStr(titulacao);
        
        Tela3 tela3 = new Tela3();
        tela3.setVisible(true);
        
        tela3.adicionarLinha("Disciplina: " + disciplina);
        tela3.adicionarLinha("Turno: " + strTurno);
        tela3.adicionarLinha("-----------------------------------------");
        tela3.adicionarLinha("Professor: " + nomeProfessor);
        tela3.adicionarLinha("Titulação: " + strTitulacao);
        tela3.adicionarLinha("-----------------------------------------");
        
        escreverAlunos(tela3);
    }//GEN-LAST:event_jBtnListarDadosActionPerformed
    
    public void escreverAlunos(Tela3 tela3){
        ArrayList<Aluno> listaAlunos = turma.getAlunos();
        
        int numAlunos = listaAlunos.size();
        
        tela3.adicionarLinha("Total de alunos: " + numAlunos);
        
        for (Aluno alunoAtual : listaAlunos){
            tela3.adicionarLinha(alunoAtual.getNome() + " " + alunoAtual.getMatricula() + 
                    " - Nota ENEM: " + format.format(alunoAtual.getNotaEnem()));
        }
        
        Aluno alunoMelhorNota = turma.obterAlunoMelhorNotaEnem();
        
        tela3.adicionarLinha("Aluno(a) com a melhor nota: " + alunoMelhorNota.getNome() + 
                " - (" + format.format(alunoMelhorNota.getNotaEnem()) + ")");
    }
    
    public void cadastrarTurma(){
        if (!turmaCadastrada){
            String disciplina = jTFDisciplina.getText();
            Turno turno = retornaTurno();
            turma = new Turma(disciplina, turno);
            
            String nomeProfessor = jTFNomeProfessor.getText();
            Titulacao titulacao = retornaTitulacao();           
            professor = new Professor(nomeProfessor, titulacao);
            turma.setProfessor(professor);
            
            turmaCadastrada = true;
        }
    }
    
    public String titulacaoParaStr(Titulacao titulacao){
        String strTitulacao = "";
        
        switch (titulacao){
            case Titulacao.GRADUACAO:
                strTitulacao = "Graduação";
                break;
            case Titulacao.MESTRADO:
                strTitulacao = "Mestrado";
                break;
            case Titulacao.DOUTORADO:
                strTitulacao = "Doutorado";
                break;
        }
        
        return strTitulacao;
    }
    
    public Titulacao retornaTitulacao(){
        Titulacao titulacao = null;
        
        if (jRBGraduacao.isSelected()){
            titulacao = Titulacao.GRADUACAO;
        } else if (jRBMestrado.isSelected()){
            titulacao = Titulacao.MESTRADO;
        } else if (jRBDoutorado.isSelected()){
            titulacao = Titulacao.DOUTORADO;
        }   
        
        return titulacao;
    }
    
    public String turnoParaStr(Turno turno){
        String strTurno = "";
        
        switch (turno){
            case Turno.MATUTINO:
                strTurno = "Matutino";
                break;
            case Turno.VESPERTINO:
                strTurno = "Vespertino";
                break;
            case Turno.NOTURNO:
                strTurno = "Noturno";
                break;
        }
        
        return strTurno;
    }
    
    public Turno retornaTurno(){
        Turno turno = null;
        
        if (jRBMatutino.isSelected()){
            turno = Turno.MATUTINO;
        } else if (jRBVespertino.isSelected()){
            turno = Turno.VESPERTINO;
        } else if (jRBNoturno.isSelected()){
            turno = Turno.NOTURNO;
        }
        
        return turno;
    }
    
    public void cadastrarAluno(String nomeAluno, int numMatricula, double notaEnem, Tela2Aluno tela2){
        Aluno aluno = new Aluno(numMatricula, nomeAluno, notaEnem);
        turma.incluirAluno(aluno);
        
        JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso");
        tela2.dispose();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1TurmaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1TurmaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1TurmaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1TurmaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1TurmaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupTitulacao;
    private javax.swing.ButtonGroup btnGroupTurno;
    private javax.swing.JButton jBtnIncluirAluno;
    private javax.swing.JButton jBtnListarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBDoutorado;
    private javax.swing.JRadioButton jRBGraduacao;
    private javax.swing.JRadioButton jRBMatutino;
    private javax.swing.JRadioButton jRBMestrado;
    private javax.swing.JRadioButton jRBNoturno;
    private javax.swing.JRadioButton jRBVespertino;
    private javax.swing.JTextField jTFDisciplina;
    private javax.swing.JTextField jTFEmailProfessor;
    private javax.swing.JTextField jTFNomeProfessor;
    // End of variables declaration//GEN-END:variables
}
