/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

/**
 *
 * Nome: Felipe Boos
 */

import Classes.DiaSemana;
import Classes.IngressoCinema;
import javax.swing.*;

public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBEstudante = new javax.swing.JCheckBox();
        jResultado = new javax.swing.JLabel();
        jBtnCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCBDomingo = new javax.swing.JCheckBox();
        jCBSegunda = new javax.swing.JCheckBox();
        jCBTerca = new javax.swing.JCheckBox();
        jCBQuarta = new javax.swing.JCheckBox();
        jCBQuinta = new javax.swing.JCheckBox();
        jCBSexta = new javax.swing.JCheckBox();
        jCBSabado = new javax.swing.JCheckBox();
        jLValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCBEstudante.setText("Estudante");
        jCBEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstudanteActionPerformed(evt);
            }
        });

        jBtnCalcular.setText("Calcular");
        jBtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularActionPerformed(evt);
            }
        });

        jLabel1.setText("Dia da semana: ");

        jCBDomingo.setText("Domingo");
        jCBDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDomingoActionPerformed(evt);
            }
        });

        jCBSegunda.setText("Segunda-Feira");
        jCBSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSegundaActionPerformed(evt);
            }
        });

        jCBTerca.setText("Terça-Feira");
        jCBTerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTercaActionPerformed(evt);
            }
        });

        jCBQuarta.setText("Quarta-Feira");
        jCBQuarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBQuartaActionPerformed(evt);
            }
        });

        jCBQuinta.setText("Quinta-Feira");
        jCBQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBQuintaActionPerformed(evt);
            }
        });

        jCBSexta.setText("Sexta-Feira");
        jCBSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSextaActionPerformed(evt);
            }
        });

        jCBSabado.setText("Sábado");
        jCBSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSabadoActionPerformed(evt);
            }
        });

        jLValor.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBSabado)
                    .addComponent(jCBSexta)
                    .addComponent(jCBQuinta)
                    .addComponent(jCBQuarta)
                    .addComponent(jCBTerca)
                    .addComponent(jCBSegunda)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBEstudante)
                        .addGap(65, 65, 65)
                        .addComponent(jResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBDomingo)
                                .addGap(60, 60, 60)
                                .addComponent(jBtnCalcular))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLValor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBEstudante)
                    .addComponent(jResultado))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnCalcular)
                            .addComponent(jLValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBDomingo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBSegunda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBTerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBSexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBSabado)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public DiaSemana dia = null;
    private void jCBEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstudanteActionPerformed
        
    }//GEN-LAST:event_jCBEstudanteActionPerformed

    private void jBtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularActionPerformed
        boolean estudante = jCBEstudante.isSelected();
        
        try {
            IngressoCinema ingresso = new IngressoCinema(dia, estudante);
        
            String valorIngresso = Float.toString(ingresso.precoIngresso());
        
            jLValor.setText("R$ " + valorIngresso);
            
        } catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
 
    }//GEN-LAST:event_jBtnCalcularActionPerformed

    private void jCBDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDomingoActionPerformed
        limparTodosBotoes();
        jCBDomingo.setSelected(true);
        dia = DiaSemana.DOMINGO;
    }//GEN-LAST:event_jCBDomingoActionPerformed

    private void jCBSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSegundaActionPerformed
        limparTodosBotoes();
        jCBSegunda.setSelected(true);
        dia = DiaSemana.SEGUNDA;
    }//GEN-LAST:event_jCBSegundaActionPerformed

    private void jCBTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTercaActionPerformed
        limparTodosBotoes();
        jCBTerca.setSelected(true);
        dia = DiaSemana.TERCA;
    }//GEN-LAST:event_jCBTercaActionPerformed

    private void jCBQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBQuartaActionPerformed
        limparTodosBotoes();
        jCBQuarta.setSelected(true);
        dia = DiaSemana.QUARTA;
    }//GEN-LAST:event_jCBQuartaActionPerformed

    private void jCBQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBQuintaActionPerformed
        limparTodosBotoes();
        jCBQuinta.setSelected(true);
        dia = DiaSemana.QUINTA;
    }//GEN-LAST:event_jCBQuintaActionPerformed

    private void jCBSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSextaActionPerformed
        limparTodosBotoes();
        jCBSexta.setSelected(true);
        dia = DiaSemana.SEXTA;
    }//GEN-LAST:event_jCBSextaActionPerformed

    private void jCBSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSabadoActionPerformed
        limparTodosBotoes();
        jCBSabado.setSelected(true);
        dia = DiaSemana.SABADO;
    }//GEN-LAST:event_jCBSabadoActionPerformed

    private void limparTodosBotoes(){
        jCBDomingo.setSelected(false);
        jCBSegunda.setSelected(false);
        jCBTerca.setSelected(false);
        jCBQuarta.setSelected(false);
        jCBQuinta.setSelected(false);
        jCBSexta.setSelected(false);
        jCBSabado.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCalcular;
    private javax.swing.JCheckBox jCBDomingo;
    private javax.swing.JCheckBox jCBEstudante;
    private javax.swing.JCheckBox jCBQuarta;
    private javax.swing.JCheckBox jCBQuinta;
    private javax.swing.JCheckBox jCBSabado;
    private javax.swing.JCheckBox jCBSegunda;
    private javax.swing.JCheckBox jCBSexta;
    private javax.swing.JCheckBox jCBTerca;
    private javax.swing.JTextField jLValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jResultado;
    // End of variables declaration//GEN-END:variables
}
