/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exe01.Tela;

import Exe01.Enum.FaixaIrpf;
import Exe01.Funcionario.Funcionario;
import java.text.DecimalFormat;

/**
 *
 * @author Felipe Boos
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFSalario = new javax.swing.JTextField();
        jBtnAvaliar = new javax.swing.JButton();
        jTFaixa = new javax.swing.JLabel();
        jTIrpf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Salário:");

        jTFSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSalarioActionPerformed(evt);
            }
        });

        jBtnAvaliar.setText("Avaliar");
        jBtnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvaliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAvaliar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTIrpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(jTFaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jBtnAvaliar)
                .addGap(33, 33, 33)
                .addComponent(jTFaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTIrpf)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSalarioActionPerformed

    private void jBtnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvaliarActionPerformed
        double salario = Double.valueOf(jTFSalario.getText());
        
        Funcionario funcionario = new Funcionario("x", salario);
        
        FaixaIrpf faixaIrpf = funcionario.identificarFaixaIRPF();
        
        int numFaixa;
        
            switch (faixaIrpf){
                case FaixaIrpf.PRIMEIRA:
                    numFaixa = 1;
                    break;
                case FaixaIrpf.SEGUNDA:
                    numFaixa = 2;
                    break;
                case FaixaIrpf.TERCEIRA:
                    numFaixa = 3;
                    break;
                case FaixaIrpf.QUARTA:
                    numFaixa = 4;
                    break;
                default:
                    numFaixa = 5;
                    break;
            }
            
            jTFaixa.setText("O salário está na " + numFaixa + "ª faixa");
            
            double valorIrpf = funcionario.calcularIRPF();
            
            String valorIrpfFormatado = irpfDoubleParaStringComVirgula(valorIrpf);
            
            jTIrpf.setText("O imposto a pagar é de R$ " + valorIrpfFormatado);
    }//GEN-LAST:event_jBtnAvaliarActionPerformed

    public String irpfDoubleParaStringComVirgula(double irpf){
        DecimalFormat format = new DecimalFormat("0.00");
        
        String irpfDuasCasas = format.format(irpf);
        
        
        return irpfDuasCasas;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAvaliar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFSalario;
    private javax.swing.JLabel jTFaixa;
    private javax.swing.JLabel jTIrpf;
    // End of variables declaration//GEN-END:variables
}
