/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author Felipe Boos
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jBtnVirgula = new javax.swing.JButton();
        jBtnIgual = new javax.swing.JButton();
        jBtnZero = new javax.swing.JButton();
        jBtnSomar = new javax.swing.JButton();
        jBtnUm = new javax.swing.JButton();
        jBtnDois = new javax.swing.JButton();
        jBtnTres = new javax.swing.JButton();
        jBtnSubtrair = new javax.swing.JButton();
        jBtnQuatro = new javax.swing.JButton();
        jBtnCinco = new javax.swing.JButton();
        jBtnSeis = new javax.swing.JButton();
        jBtnMultiplicar = new javax.swing.JButton();
        jBtnSete = new javax.swing.JButton();
        jBtnOito = new javax.swing.JButton();
        jBtnNove = new javax.swing.JButton();
        jBtnCE = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnApagar = new javax.swing.JButton();
        jBtnDividir = new javax.swing.JButton();
        jLResultado = new javax.swing.JLabel();
        jLTextoAcima = new javax.swing.JLabel();

        jButton17.setText("jButton1");

        jButton18.setText("jButton1");

        jButton19.setText("jButton1");

        jButton20.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnVirgula.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jBtnVirgula.setText(",");
        jBtnVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVirgulaActionPerformed(evt);
            }
        });

        jBtnIgual.setBackground(new java.awt.Color(0, 230, 0));
        jBtnIgual.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBtnIgual.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIgual.setText("=");
        jBtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIgualActionPerformed(evt);
            }
        });

        jBtnZero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnZero.setText("0");
        jBtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZeroActionPerformed(evt);
            }
        });

        jBtnSomar.setBackground(new java.awt.Color(125, 125, 125));
        jBtnSomar.setFont(new java.awt.Font("Segoe UI", 0, 33)); // NOI18N
        jBtnSomar.setText("+");
        jBtnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSomarActionPerformed(evt);
            }
        });

        jBtnUm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnUm.setText("1");
        jBtnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUmActionPerformed(evt);
            }
        });

        jBtnDois.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnDois.setText("2");
        jBtnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoisActionPerformed(evt);
            }
        });

        jBtnTres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnTres.setText("3");
        jBtnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTresActionPerformed(evt);
            }
        });

        jBtnSubtrair.setBackground(new java.awt.Color(125, 125, 125));
        jBtnSubtrair.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jBtnSubtrair.setText("-");
        jBtnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubtrairActionPerformed(evt);
            }
        });

        jBtnQuatro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnQuatro.setText("4");
        jBtnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuatroActionPerformed(evt);
            }
        });

        jBtnCinco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnCinco.setText("5");
        jBtnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCincoActionPerformed(evt);
            }
        });

        jBtnSeis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnSeis.setText("6");
        jBtnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeisActionPerformed(evt);
            }
        });

        jBtnMultiplicar.setBackground(new java.awt.Color(125, 125, 125));
        jBtnMultiplicar.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jBtnMultiplicar.setText("x");
        jBtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplicarActionPerformed(evt);
            }
        });

        jBtnSete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnSete.setText("7");
        jBtnSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeteActionPerformed(evt);
            }
        });

        jBtnOito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnOito.setText("8");
        jBtnOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOitoActionPerformed(evt);
            }
        });

        jBtnNove.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnNove.setText("9");
        jBtnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNoveActionPerformed(evt);
            }
        });

        jBtnCE.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnCE.setText("CE");
        jBtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCEActionPerformed(evt);
            }
        });

        jBtnC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });

        jBtnApagar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBtnApagar.setText("←");
        jBtnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApagarActionPerformed(evt);
            }
        });

        jBtnDividir.setBackground(new java.awt.Color(125, 125, 125));
        jBtnDividir.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBtnDividir.setText("÷");
        jBtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDividirActionPerformed(evt);
            }
        });

        jLResultado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLResultado.setText("0");
        jLResultado.setToolTipText("");

        jLTextoAcima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLTextoAcima.setForeground(new java.awt.Color(120, 120, 120));
        jLTextoAcima.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(jBtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLTextoAcima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLTextoAcima, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jBtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnZero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVirgula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    double num1 = 0;
    double num2 = 0;
    double resultado = 0;
    boolean reescreverNum = false;
    boolean podeApagar = true;
    String operador = " ";
    
    private void adNumOuVirgula(String numOuVirgula){
        if (reescreverNum){
            jLResultado.setText("0");
            reescreverNum = false;
        }
        String numAtualizado = jLResultado.getText();
        
        if (numAtualizado.equals("0") && !numOuVirgula.equals(",")){
            numAtualizado = numOuVirgula;
        } else {
            numAtualizado += numOuVirgula;
        }
        
        jLResultado.setText(numAtualizado);
        
        podeApagar = true;
    }
    
    private void setNum1(){
        String strNum1 = jLResultado.getText();
        
        String num1CPonto = strNum1.replace(",", ".");
        
        num1 = Double.valueOf(num1CPonto);
    }
    
    private void setNum2(){
        String strNum2 = jLResultado.getText();
        
        String num1CPonto = strNum2.replace(",", ".");
        
        num2 = Double.valueOf(num1CPonto); 
    }
    
    private String numeroFormatado(double numero){
        String strNum = Double.toString(numero);
        
        char ultimoCaracter = strNum.charAt(strNum.length() - 1);
        
        String strUltimoC = new String(new char[]{ultimoCaracter});
        
        String substring;
        
        if (strNum.contains(".")){
            while(strUltimoC.equals("0")){
                substring = strNum.substring(0, strNum.length() - 1);
                
                strNum = substring;
                
                ultimoCaracter = strNum.charAt(strNum.length() - 1);
                strUltimoC = new String(new char[]{ultimoCaracter});
            }
        }
        
        if (strUltimoC.equals(".")){
            substring = strNum.substring(0, strNum.length() - 1);
            strNum = substring;
        }
        
        return strNum.replace(".", ",");
    }
    
    private void escreverCampoAcima(){
        jLTextoAcima.setText(numeroFormatado(num1) + " " + operador);
        
    }
    
    private void setOperador(String charOp){
        operador = charOp;
        if (!reescreverNum){
            setNum1();
        }
        escreverCampoAcima();
        reescreverNum = true;
    }
    
    private void jBtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZeroActionPerformed
        adNumOuVirgula("0");
    }//GEN-LAST:event_jBtnZeroActionPerformed

    private void jBtnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUmActionPerformed
        adNumOuVirgula("1");
    }//GEN-LAST:event_jBtnUmActionPerformed

    private void jBtnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoisActionPerformed
        adNumOuVirgula("2");
    }//GEN-LAST:event_jBtnDoisActionPerformed

    private void jBtnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTresActionPerformed
        adNumOuVirgula("3");
    }//GEN-LAST:event_jBtnTresActionPerformed

    private void jBtnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuatroActionPerformed
        adNumOuVirgula("4");
    }//GEN-LAST:event_jBtnQuatroActionPerformed

    private void jBtnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCincoActionPerformed
        adNumOuVirgula("5");
    }//GEN-LAST:event_jBtnCincoActionPerformed

    private void jBtnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeisActionPerformed
        adNumOuVirgula("6");
    }//GEN-LAST:event_jBtnSeisActionPerformed

    private void jBtnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeteActionPerformed
        adNumOuVirgula("7");
    }//GEN-LAST:event_jBtnSeteActionPerformed

    private void jBtnOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOitoActionPerformed
        adNumOuVirgula("8");
    }//GEN-LAST:event_jBtnOitoActionPerformed

    private void jBtnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNoveActionPerformed
        adNumOuVirgula("9");
    }//GEN-LAST:event_jBtnNoveActionPerformed

    private void jBtnVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVirgulaActionPerformed
        if (!jLResultado.getText().contains(",")){
            adNumOuVirgula(",");
        }
    }//GEN-LAST:event_jBtnVirgulaActionPerformed

    private void jBtnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSomarActionPerformed
        setOperador("+");
    }//GEN-LAST:event_jBtnSomarActionPerformed

    private void jBtnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtrairActionPerformed
        setOperador("-");
    }//GEN-LAST:event_jBtnSubtrairActionPerformed

    private void jBtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplicarActionPerformed
        setOperador("x");
    }//GEN-LAST:event_jBtnMultiplicarActionPerformed

    private void jBtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDividirActionPerformed
        setOperador("÷");
    }//GEN-LAST:event_jBtnDividirActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        jLResultado.setText("0");
        jLTextoAcima.setText(" ");
        num1 = 0;
        num2 = 0;
        reescreverNum = false;
        resultado = 0;
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCEActionPerformed
        jLResultado.setText("0");
        num2 = 0;
    }//GEN-LAST:event_jBtnCEActionPerformed

    private void jBtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIgualActionPerformed
        setNum2();
        resultado = 0;
        
        switch (operador){
            case "+":
                resultado = num1 + num2;
                break;
            case "-":
                resultado = num1 - num2;
                break;
            case "x":
                resultado = num1 * num2;
                break;
            case "÷":
                resultado = num1 / num2;
                break;
            default:
                break;
        }
        jLResultado.setText(numeroFormatado(resultado));
        jLTextoAcima.setText("");
        reescreverNum = true;
        podeApagar = false;
        setNum1();
    }//GEN-LAST:event_jBtnIgualActionPerformed

    private void jBtnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApagarActionPerformed
        if (podeApagar){
          String strResultado = jLResultado.getText();
        
            String novaString = strResultado.substring(0, strResultado.length() - 1);
        
            if (novaString.equals("")){
                jLResultado.setText("0");
            } else {
                jLResultado.setText(novaString);
            }  
        }
    }//GEN-LAST:event_jBtnApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApagar;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnCE;
    private javax.swing.JButton jBtnCinco;
    private javax.swing.JButton jBtnDividir;
    private javax.swing.JButton jBtnDois;
    private javax.swing.JButton jBtnIgual;
    private javax.swing.JButton jBtnMultiplicar;
    private javax.swing.JButton jBtnNove;
    private javax.swing.JButton jBtnOito;
    private javax.swing.JButton jBtnQuatro;
    private javax.swing.JButton jBtnSeis;
    private javax.swing.JButton jBtnSete;
    private javax.swing.JButton jBtnSomar;
    private javax.swing.JButton jBtnSubtrair;
    private javax.swing.JButton jBtnTres;
    private javax.swing.JButton jBtnUm;
    private javax.swing.JButton jBtnVirgula;
    private javax.swing.JButton jBtnZero;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLTextoAcima;
    // End of variables declaration//GEN-END:variables
}
